version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${P_DB}
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "5432:5432"

  test_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_${P_DB}
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "6000:5432"

  back:
    build:
      context: .
    volumes:
      - .:/backend
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    ports:
      - "8000:8000"

