"""update model chat

Revision ID: 0f3fa19855ee
Revises: c3a9a4c72788
Create Date: 2024-03-13 15:37:27.374319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3fa19855ee'
down_revision: Union[str, None] = 'c3a9a4c72788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('first_user_id', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('second_user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'second_user_id')
    op.drop_column('chat', 'first_user_id')
    # ### end Alembic commands ###
