"""add text to message model

Revision ID: 89dfa444fc0f
Revises: 0f3fa19855ee
Create Date: 2024-03-13 15:45:08.373541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dfa444fc0f'
down_revision: Union[str, None] = '0f3fa19855ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'text')
    # ### end Alembic commands ###
