"""chat_message_new

Revision ID: c6f8b5571efc
Revises: 89dfa444fc0f
Create Date: 2024-03-19 11:46:44.574810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f8b5571efc'
down_revision: Union[str, None] = '89dfa444fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.drop_table('chat')
    op.add_column('message', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('attachment', sa.String(length=255), nullable=True))
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'message', 'user_account', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user_account', ['receiver_id'], ['id'])
    op.drop_column('message', 'recipient_id')
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['id'])
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('message', 'attachment')
    op.drop_column('message', 'receiver_id')
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('second_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_pkey')
    )
    # ### end Alembic commands ###
